version: "3.8"

services:
    kafka-connect:
        image: confluentinc/cp-kafka-connect:7.6.2
        depends_on:
            - kafka
        ports:
            - "8083:8083"
        environment:
            CONNECT_BOOTSTRAP_SERVERS: localhost:9092
            CONNECT_REST_PORT: 8083
            CONNECT_GROUP_ID: "connect-cluster"
            CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
            CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
            CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
            CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
            CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: false
            CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: false
            CONNECT_PLUGIN_PATH: "/usr/share/java"
        command:
            - bash
            - -c
            - |
                echo "Installing elasticsearch sink Connector"
                confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest
                #
                echo "Launching Kafka Connect worker"
                /etc/confluent/docker/run &
                #
                sleep infinity

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        depends_on:
            - kafka
            - kafka-connect
        ports:
            - "8080:8080"
        environment:
            DYNAMIC_CONFIG_ENABLED: "true"
            KAFKA_CLUSTERS_0_NAME: "local"
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "localhost:9092"
            KAFKA_CLUSTERS_0_ZOOKEEPER: "localhost:2181"
            KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: "kafka-connect"
            KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: "http://kafka-connect:8083"

networks:
    default:
        name: kafka_network
