version: "3.8"

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.2
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"
        volumes: 
            - ./zoo/data:/var/lib/zookeeper/data
            - ./zoo/log:/var/lib/zookeeper/log
    kafka:
        image: confluentinc/cp-kafka:7.6.2
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
            - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_LOG4J_LOGGERS: "org.apache.kafka=INFO"
        volumes: 
          - ./kafka/data:/var/lib/kafka/data
    kafka-connect:
        image: confluentinc/cp-kafka-connect:7.6.2
        depends_on:
            - kafka
        ports:
            - "8083:8083"
        environment:
            CONNECT_BOOTSTRAP_SERVERS: kafka:19092
            CONNECT_REST_PORT: 8083
            CONNECT_GROUP_ID: "connect-cluster"
            CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
            CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
            CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
            CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
            CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: false
            CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: false
            CONNECT_PLUGIN_PATH: "/usr/share/java"
        command:
            - bash
            - -c
            - |
                echo "Installing elasticsearch sink Connector"
                confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest
                #
                echo "Launching Kafka Connect worker"
                /etc/confluent/docker/run &
                #
                sleep infinity

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        depends_on:
            - kafka
            - kafka-connect
        ports:
            - "8080:8080"
        environment:
            DYNAMIC_CONFIG_ENABLED: "true"
            KAFKA_CLUSTERS_0_NAME: "local"
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:19092"
            KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
            KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: "kafka-connect"
            KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: "http://kafka-connect:8083"

networks:
    default:
        name: kafka_network
